<?php

namespace Otus\Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Bitrix\Main\Localization\Loc;
use Bitrix\Main\ORM\Fields\StringField;
use Otus\Models\AbstractIblockPropertyValuesTable;

class HealersPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

    public static function getMap(): array
    {
        $map = [
            new \Bitrix\Main\ORM\Fields\IntegerField('IBLOCK_ELEMENT_ID', [
                'primary' => true,
            ]),
            'NAME' => new StringField('NAME'),
            'SURNAME' => new StringField('SURNAME'),
            'SECOND_NAME' => new StringField('SECOND_NAME'),
            'PROCEDURE' => new ReferenceField(
                'PROCEDURE',
                ProceduresPropertyValuesTable::class,
                ['=this.PROCEDURE_ID' => 'ref.PROCEDURE_ID']
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
