<?php

namespace Otus\Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Otus\Models\AbstractIblockPropertyValuesTable;

class HealersPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

    public static function getMap(): array
    {
        $map = [
            'PROCEDURE' => new ReferenceField(
                'PROCEDURE',
                ProceduresPropertyValuesTable::class,
                ['=this.PROCEDURE_ID' => 'ref.PROCEDURE_ID']
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
