<?php

namespace Otus\Models\Lists;

use Bitrix\Main\Entity\ReferenceField;
use Bitrix\Main\ORM\Fields\StringField;
use Otus\Models\AbstractIblockPropertyValuesTable;

class ProceduresPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 17;
    public static function getMap(): array
    {
        $map = [
            new \Bitrix\Main\ORM\Fields\IntegerField('IBLOCK_ELEMENT_ID', [
                'primary' => true,
            ]),
            new \Bitrix\Main\ORM\Fields\StringField('IBLOCK_ELEMENT_NAME', [
            ]),
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
